# Generated by Django 4.0.4 on 2025-03-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
