# Generated by Django 4.0.4 on 2025-03-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_reviews_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reviews',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
